# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170806_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_1',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
